spring:
  datasource:
    url: jdbc:mysql://mysql-master/db_smart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
logging:
  config: logback-spring.xml


