version: "3"
services:
  nginx-container:
    image: nginx:1.16.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/:/etc/nginx/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
  app_80:
    build: ./app/
    ports:
      - "8080:8080"


